#!/bin/bash

function display_error
{
    name=`echo "$1" | sed 's|^.*/||'`
    if [[ "$2" == "--no-file" ]]
    then
        echo -e "${name}: error: ${3}: No such file" 1>&2
    elif [[ "$2" == "--wget-fail" ]]
    then
        echo -e "${name}: error: URL:${3}: Download failed" 1>&2
    else
        echo -e "${name}: fatal error!\n\n"\
                "\bTry \`$name --help' for more information." 1>&2
        exit
    fi
}

function display_help
{
    echo "You came here expecting help, but all you receive is sadness."
    ## TODO: Actual help mode. Add more options to script.
    exit
}

if [ $# -eq 0 ]
then
    display_error "$0"
fi

failure=false
for file in "$@"
do
    if [[ "$file" == "--help" ]]
    then
        display_help
    elif ! [ -f "$file" ]
    then
        display_error "$0" "--no-file" "$file"
        failure=true
    fi
done
if $failure
then
    display_error "$0"
fi

for file in "$@"
do
    echo '['`date +"%F %T"`']' "Begin file:" "$file" 1>&2
    while read -r line
    do
        if [ "$line" ]
        then
            if ! [[ "$line" == "#"* ]]
            then
                array=($line)
                if [ "${array[1]}" ]
                then
                    echo '['`date +"%F %T"`']' "Begin:" "URL:${array[0]}" '->' "${array[1]}" 1>&2
                    wget -qN "${array[0]}" -O "${array[1]}" \
                    && echo '['`date +"%F %T"`']' "Finish:" "URL:${array[0]}" 1>&2 \
                    || display_error "$0" "--wget-fail" "${array[0]}" &
                else
                    name=`echo "$line" | sed 's|^.*/||'`
                    echo '['`date +"%F %T"`']' "Begin:" "URL:$line" '->' "$name" 1>&2
                    wget -qN "$line" -O "$name" \
                    && echo '['`date +"%F %T"`']' "Finish:" "URL:$line" 1>&2 \
                    || display_error "$0" "--wget-fail" "$line" &
                fi
            fi
        fi
    done < "$file"
    wait
    echo '['`date +"%F %T"`']' "Finish file:" "$file" 1>&2
done

